REDIS_COVER_START_CHANNEL = 'REDIS_COVER_START_CHANNEL'
REDIS_COVER_FINISHED_CHANNEL = 'REDIS_COVER_FINISHED_CHANNEL'

TOPIC_COVER_STARTED = 'TOPIC_COVER_STARTED'
TOPIC_COVER_FINISHED = 'TOPIC_COVER_FINISHED'

LATEST_NEWS_PAGINATION_SIZE = 30
