REDIS_COVER_START_CHANNEL = 'REDIS_COVER_START_CHANNEL'
REDIS_COVER_FINISHED_CHANNEL = 'REDIS_COVER_FINISHED_CHANNEL'

TOPIC_COVER_STARTED = 'TOPIC_COVER_STARTED'
TOPIC_COVER_FINISHED = 'TOPIC_COVER_FINISHED'

LATEST_NEWS_PAGINATION_SIZE = 30
NEWS_RECOMMENDATION_SIZE = 5

DEFAULT_NEWS_SIZE = 100
DEFAULT_CORPUS_SIZE = 1000

CORPUS_EXPIRATION_HOURS = 3
CORPUS_EXPIRATION_TIME = CORPUS_EXPIRATION_HOURS * 60 * 60
