REDIS_COVER_START_CHANNEL = 'REDIS_COVER_START_CHANNEL'
REDIS_COVER_SUCCESS_CHANNEL = 'REDIS_COVER_SUCCESS_CHANNEL'
REDIS_COVER_ERROR_CHANNEL = 'REDIS_COVER_ERROR_CHANNEL'

COVER_START = 'COVER_START'
COVER_SUCCESS = 'COVER_SUCCESS'
COVER_ERROR = 'COVER_ERROR'

LATEST_NEWS_PAGINATION_SIZE = 30
NEWS_RECOMMENDATION_SIZE = 5

DEFAULT_NEWS_SIZE = 100
DEFAULT_CORPUS_SIZE = 1000

CORPUS_EXPIRATION_HOURS = 3
CORPUS_EXPIRATION_TIME = CORPUS_EXPIRATION_HOURS * 60 * 60
