"""empty message

Revision ID: 0346aa448a09
Revises: 4d29960ef450
Create Date: 2016-04-24 19:22:05.548576

"""

# revision identifiers, used by Alembic.
revision = '0346aa448a09'
down_revision = '4d29960ef450'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column(
        'created', sa.DateTime(), server_default=sa.func.now(),
        nullable=False))
    op.add_column('news', sa.Column(
        'updated', sa.DateTime(), server_default=sa.func.now(),
        nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'updated')
    op.drop_column('news', 'created')
    ### end Alembic commands ###
