"""empty message

Revision ID: 3a845b6b0d9e
Revises: a748217173c3
Create Date: 2016-05-28 17:06:27.361710

"""

# revision identifiers, used by Alembic.
revision = '3a845b6b0d9e'
down_revision = 'a748217173c3'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('author', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('news', sa.Column('published', sa.DateTime(), nullable=True))
    op.add_column('news', sa.Column('summary', sa.Text(), server_default='', nullable=False))
    op.add_column('news', sa.Column('title', sa.Text(), server_default='', nullable=False))
    op.drop_constraint('news_src_id_fkey', 'news', type_='foreignkey')
    op.create_foreign_key(None, 'news', 'news', ['parent_id'], ['id'])
    op.drop_column('news', 'src_id')
    op.add_column('schedule', sa.Column('news_type', sa.String(), server_default='url', nullable=False))
    op.add_column('schedule', sa.Column('options', sqlalchemy_utils.types.json.JSONType(), server_default='{}', nullable=False))
    op.drop_column('schedule', 'blacklist')
    op.drop_column('schedule', 'brothers')
    op.drop_column('schedule', 'latest_task')
    op.drop_column('schedule', 'max_depth')
    op.drop_column('schedule', 'max_dist')
    op.drop_column('schedule', 'max_visit')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('max_visit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('schedule', sa.Column('max_dist', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('schedule', sa.Column('max_depth', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('schedule', sa.Column('latest_task', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('schedule', sa.Column('brothers', postgresql.JSON(), autoincrement=False, nullable=False))
    op.add_column('schedule', sa.Column('blacklist', postgresql.JSON(), autoincrement=False, nullable=False))
    op.drop_column('schedule', 'options')
    op.drop_column('schedule', 'news_type')
    op.add_column('news', sa.Column('src_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'news', type_='foreignkey')
    op.create_foreign_key('news_src_id_fkey', 'news', 'news', ['src_id'], ['id'])
    op.drop_column('news', 'title')
    op.drop_column('news', 'summary')
    op.drop_column('news', 'published')
    op.drop_column('news', 'parent_id')
    op.drop_column('news', 'image')
    op.drop_column('news', 'author')
    ### end Alembic commands ###
