"""empty message

Revision ID: 452da1439a56
Revises: a3cebcc6363d
Create Date: 2016-03-09 16:29:16.840591

"""

# revision identifiers, used by Alembic.
revision = '452da1439a56'
down_revision = 'a3cebcc6363d'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sqlalchemy_utils.types.url.URLType(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('max_dist', sa.Integer(), nullable=True),
    sa.Column('max_depth', sa.Integer(), nullable=True),
    sa.Column('blacklist', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('brothers', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'url')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    ### end Alembic commands ###
