"""empty message

Revision ID: 4d29960ef450
Revises: 58f7604cd5b0
Create Date: 2016-04-18 23:08:30.259263

"""

# revision identifiers, used by Alembic.
revision = '4d29960ef450'
down_revision = '58f7604cd5b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('max_visit', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'max_visit')
    ### end Alembic commands ###
