"""empty message

Revision ID: c12f49bb1296
Revises: cf9fdb9787da
Create Date: 2016-05-02 22:05:08.838787

"""

# revision identifiers, used by Alembic.
revision = 'c12f49bb1296'
down_revision = 'cf9fdb9787da'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SVM',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serialized', sa.LargeBinary(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('corpus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpus.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('MLP')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MLP',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"MLP_id_seq"\'::regclass)'), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('corpus_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpus.id'], name='MLP_corpus_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='MLP_pkey')
    )
    op.drop_table('SVM')
    ### end Alembic commands ###
