"""empty message

Revision ID: e0d3d2c72b5b
Revises: None
Create Date: 2016-04-01 16:54:06.198013

"""

# revision identifiers, used by Alembic.
revision = 'e0d3d2c72b5b'
down_revision = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from components.server.users.models import User


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sqlalchemy_utils.types.choice.ChoiceType(User.ROLES), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sqlalchemy_utils.types.url.URLType(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('max_dist', sa.Integer(), nullable=True),
    sa.Column('max_depth', sa.Integer(), nullable=True),
    sa.Column('blacklist', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('brothers', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'url')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sqlalchemy_utils.types.url.URLType(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('src_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['src_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'url')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    op.drop_table('schedule')
    op.drop_table('user')
    ### end Alembic commands ###
